/** User-facing copy that is safe to adjust without touching page logic. */
export const TEXTS = {
  pages: {
    todayDescription: "今天又是元气满满的一天，看看有哪些安排吧",
    tasksDescription: "今日事，今日毕",
    campusEyebrow: "校园服务",
    settingsDescription: "管理提醒、显示和隐私",
    reminderDescription: "仅允许输入整数，最长可提前7天提醒",
    quietHoursDescription: "只有勾选“静默时段仍提醒”的事项才会在静默时段发出提醒",
    credit: "由晏冬阳 崔谭煦 高靖凯制作",
    close: "关闭",
  },
  common: {
    storageFull: "对话中的图片较多，本机存储空间不足",
    resetDone: "个人信息已重置",
    profileSaved: "个人资料已保存",
    coursesCleared: "课表已清空",
    notificationsRead: "通知已全部已读",
    blankConversation: "当前已是空白对话，请先发送一条消息",
    campusLoadFailed: "校园数据加载失败",
  },
  welcome: {
    nameRequired: "请输入你的昵称",
    greeting: (name: string) => `欢迎你，${name}`,
  },
  auth: {
    formIncomplete: "请分别完整填写两套账号和密码",
    verifyFailed: "账号验证失败",
    saveFailed: "账号保存失败",
    saved: "校园账号已加密保存在本机",
    deleteFailed: "无法删除校园账号配置",
    deleted: "已删除本机校园账号和登录会话",
    campusRequired: "请先在设置中绑定教务系统账号",
    coursesQueryFailed: "个人课表查询失败",
    credentialsRequired: "请先绑定统一身份认证和教务系统账号",
  },
  security: {
    browserConfigOnly: "浏览器开发模式不保存密码或 API Key，请使用桌面客户端完成本机配置",
    accountStorageUnavailable: "当前系统无法安全保存账号和密钥",
    aiCredentialMissing: "AI 凭据未配置",
    cookieSingleLine: "Cookie 文件必须是单行请求头或 JSON 对象",
    requestTooLarge: "请求内容过大",
  },
  validation: {
    nicknameRequired: "昵称不能为空",
    avatarType: "请选择 PNG、JPG 或 WebP 图片",
    avatarTooLarge: "头像文件不能超过 2 MB",
    avatarReadFailed: "无法读取这张图片，请换一张重试",
    taskRequired: "请填写任务内容和截止时间",
    taskDuePast: "截止时间必须晚于现在",
    courseFields: "请检查课程名和节次",
    courseWeeks: "周次只支持数字、横杠和中英文逗号，例如 1-2，4-10",
    imageType: "当前模型仅支持 PNG、JPG 和 WebP 图片",
    imageTooLarge: "单张图片不能超过 1 MB",
    imageReadFailed: "无法读取这张图片",
    messageFormat: "消息格式无效",
    messageRole: "消息角色无效",
    toolMessageId: "工具消息缺少 tool_call_id",
    attachmentFormat: "附件格式无效",
    attachmentType: "当前模型不支持此附件格式",
    attachmentSize: "附件无效或超过 1 MB",
    toolCallFormat: "工具调用格式无效",
    toolFunctionMissing: "工具调用缺少 function",
  },
  tasks: {
    confirmDelete: "确认删除",
    added: "任务已添加",
    updated: "任务已更新",
    deleted: "任务已删除",
    completed: "任务已完成",
    restored: "任务已恢复",
    assistantAdded: "任务已由助手添加",
  },
  ai: {
    modelsUnavailable: "没有读取到受支持的 DeepSeek 模型",
    configSaveFailed: "模型配置保存失败",
    configDeleteFailed: "无法删除模型配置",
    deleted: "已删除本机 API Key 和模型设置",
    configured: "DeepSeek 配置已加密保存在本机",
    configRequired: "请填写 DeepSeek API Key",
    modelRequired: "请选择一个 DeepSeek 模型",
    modelChangeFailed: "模型切换失败",
    switchedModel: (model: string) => `已切换模型：${model}`,
    noReply: "AI 服务没有返回正文",
    unavailable: "AI 服务暂时不可用",
    toolLimit: "工具调用轮数超过限制建议分步重试",
  },
  electricity: {
    queryFailed: "电费余额查询失败",
    updated: "电费余额已更新",
    unbound: "已解除宿舍绑定",
  },
  courses: {
    added: "课程已添加",
    deleted: "课程已删除",
    saved: "课程修改已保存",
    importDone: (count: number) => `课表导入完成，共写入 ${count} 门课程`,
  },
  campus: {
    summaryLoading: "正在读取官方通知并生成摘要…",
    summaryUnavailable: "暂时无法生成摘要，请查看原文链接",
    summaryFailed: "通知摘要生成失败",
    relogin: "重新登录（可能会短暂打开浏览器）",
    cacheNotice: "在线刷新失败，正在显示最近一次真实缓存请重新登录后再试",
  },
} as const;
